name: 🚨 Bug
description: Report a bug
title: "fix: "
labels: ["bug"]
projects: ["solaudity/1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is
      placeholder: "Example: The audit report fails to generate when..."
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Indiquez les versions de votre environnement si pertinent.
      value: |
        - OS: 
        - Docker: 
        - npm: 
        - Python: 
    validations:
      required: false

  - type: textarea
    id: logs-screenshots
    attributes:
      label: Logs/Screenshots
      description: Add logs or screenshots if relevant
    validations:
      required: false
