name: ⏸️ On Hold
description: Issue paused or blocked
labels: ["on-hold"]
projects: ["solaudity/1"]
body:
  - type: markdown
    attributes:
      value: |
        Mark an issue as paused or blocked.

  - type: textarea
    id: whats-on-hold
    attributes:
      label: What's on hold?
      description: Describe what is paused
      placeholder: "Example: The migration to..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: What's blocking this?
      placeholder: "Example: Waiting for..."
    validations:
      required: true
