"""add analyzer4 tables

Revision ID: 21e5d4b37e2c
Revises: b8a3e5f2fd28
Create Date: 2026-05-10 15:30:22.221662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21e5d4b37e2c'
down_revision: Union[str, Sequence[str], None] = 'b8a3e5f2fd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzer4_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='analyzer4_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('tool_version', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('stderr_output', sa.Text(), nullable=True),
    sa.Column('count_high', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_medium', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_low', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_nc', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_gas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyzer4_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyzer4_runs_audit_id'), ['audit_id'], unique=False)

    op.create_table('analyzer4_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.Enum('H', 'M', 'L', 'NC', 'GAS', name='analyzer4_issue_type', native_enum=False), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analyzer4_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyzer4_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyzer4_findings_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyzer4_findings_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer4_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyzer4_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_analyzer4_findings_audit_id'))

    op.drop_table('analyzer4_findings')
    with op.batch_alter_table('analyzer4_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyzer4_runs_audit_id'))

    op.drop_table('analyzer4_runs')
    # ### end Alembic commands ###
