"""create audits and audit attachments tables

Revision ID: 2498d71abf60
Revises: cb505b52da28
Create Date: 2026-02-12 11:50:55.875096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2498d71abf60'
down_revision: Union[str, Sequence[str], None] = 'cb505b52da28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'archived', name='audit_status', native_enum=False), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('chain', sa.Text(), nullable=True),
    sa.Column('network', sa.Text(), nullable=True),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('commit_hash', sa.Text(), nullable=True),
    sa.Column('docs_url', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['last_opened_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_owner_id'), ['owner_id'], unique=False)

    op.create_table('audit_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('file_ext', sa.Text(), nullable=False),
    sa.CheckConstraint('size_bytes > 0 AND size_bytes <= 104857600', name='ck_audit_attachments_size_bytes'),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('audit_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_attachments_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_attachments_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_attachments_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_audit_attachments_audit_id'))

    op.drop_table('audit_attachments')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_owner_id'))

    op.drop_table('audits')
    # ### end Alembic commands ###
