"""add_smtchecker_tables

Revision ID: 2552e6bcfeef
Revises: 39693a252750
Create Date: 2026-05-19 13:11:19.911400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2552e6bcfeef'
down_revision: Union[str, Sequence[str], None] = '39693a252750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtchecker_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='smtchecker_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('engine', sa.Text(), server_default=sa.text("'chc'"), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('stderr_output', sa.Text(), nullable=True),
    sa.Column('count_warnings', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_errors', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smtchecker_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smtchecker_runs_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_smtchecker_runs_scope_contract_id'), ['scope_contract_id'], unique=False)

    op.create_table('smtchecker_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', 'info', name='smtchecker_severity', native_enum=False), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('formatted_message', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['smtchecker_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smtchecker_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smtchecker_findings_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_smtchecker_findings_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtchecker_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smtchecker_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_smtchecker_findings_audit_id'))

    op.drop_table('smtchecker_findings')
    with op.batch_alter_table('smtchecker_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smtchecker_runs_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_smtchecker_runs_audit_id'))

    op.drop_table('smtchecker_runs')
    # ### end Alembic commands ###
