"""add_certora_tables

Revision ID: 39693a252750
Revises: d0980cda7662
Create Date: 2026-05-19 13:01:02.844526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39693a252750'
down_revision: Union[str, Sequence[str], None] = 'd0980cda7662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certora_specs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certora_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certora_specs_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certora_specs_scope_contract_id'), ['scope_contract_id'], unique=False)

    op.create_table('certora_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=True),
    sa.Column('spec_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='certora_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('tool_version', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('stderr_output', sa.Text(), nullable=True),
    sa.Column('count_pass', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_fail', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_timeout', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_unknown', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['certora_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certora_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certora_runs_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certora_runs_scope_contract_id'), ['scope_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certora_runs_spec_id'), ['spec_id'], unique=False)

    op.create_table('certora_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'TIMEOUT', 'UNKNOWN', 'SANITY_FAIL', name='certora_rule_status', native_enum=False), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['certora_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certora_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certora_rules_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certora_rules_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certora_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certora_rules_run_id'))
        batch_op.drop_index(batch_op.f('ix_certora_rules_audit_id'))

    op.drop_table('certora_rules')
    with op.batch_alter_table('certora_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certora_runs_spec_id'))
        batch_op.drop_index(batch_op.f('ix_certora_runs_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_certora_runs_audit_id'))

    op.drop_table('certora_runs')
    with op.batch_alter_table('certora_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certora_specs_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_certora_specs_audit_id'))

    op.drop_table('certora_specs')
    # ### end Alembic commands ###
