"""add preset to slither_runs

Revision ID: 3ae4048aa179
Revises: bda500e7d7ea
Create Date: 2026-04-13 21:59:01.475490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ae4048aa179'
down_revision: Union[str, Sequence[str], None] = 'bda500e7d7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slither_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preset', sa.Enum('all', 'high_medium', 'reentrancy', 'access_control', 'code_quality', name='slither_preset', native_enum=False), server_default=sa.text("'all'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slither_runs', schema=None) as batch_op:
        batch_op.drop_column('preset')

    # ### end Alembic commands ###
