"""add ai_vuln_scans table

Revision ID: 495e477a5a60
Revises: 4fa2f712bb51
Create Date: 2026-05-19 22:38:13.282161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '495e477a5a60'
down_revision: Union[str, Sequence[str], None] = '4fa2f712bb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_vuln_scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('vuln_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_vuln_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_vuln_scans_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_vuln_scans_contract_id'), ['contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_vuln_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_vuln_scans_contract_id'))
        batch_op.drop_index(batch_op.f('ix_ai_vuln_scans_audit_id'))

    op.drop_table('ai_vuln_scans')
    # ### end Alembic commands ###
