"""add is_contract and bytecode to scope_addresses

Revision ID: 5761c0caff77
Revises: bb0ac7541add
Create Date: 2026-03-13 15:16:40.821409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5761c0caff77'
down_revision: Union[str, Sequence[str], None] = 'bb0ac7541add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_contract', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('bytecode', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_addresses', schema=None) as batch_op:
        batch_op.drop_column('bytecode')
        batch_op.drop_column('is_contract')

    # ### end Alembic commands ###
