"""add_echidna_runs_table

Revision ID: 90ae27907782
Revises: f551a15097c3
Create Date: 2026-05-20 12:01:35.881824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90ae27907782'
down_revision: Union[str, Sequence[str], None] = 'f551a15097c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('echidna_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=False),
    sa.Column('test_mode', sa.Enum('property', 'assertion', 'overflow', 'exploration', name='echidna_test_mode', native_enum=False), server_default=sa.text("'property'"), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default=sa.text('(60)'), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='echidna_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('echidna_version', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_stdout', sa.Text(), nullable=True),
    sa.Column('raw_stderr', sa.Text(), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('count_passed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('echidna_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_echidna_runs_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_echidna_runs_scope_contract_id'), ['scope_contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('echidna_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_echidna_runs_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_echidna_runs_audit_id'))

    op.drop_table('echidna_runs')
    # ### end Alembic commands ###
