"""add ai_docs table

Revision ID: a4b2951697fc
Revises: db9bc4a54b8d
Create Date: 2026-04-09 12:18:45.490290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4b2951697fc'
down_revision: Union[str, Sequence[str], None] = 'db9bc4a54b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_docs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['scope_addresses.id'], ),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_docs_address_id'), ['address_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_docs_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_docs_contract_id'), ['contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_docs_contract_id'))
        batch_op.drop_index(batch_op.f('ix_ai_docs_audit_id'))
        batch_op.drop_index(batch_op.f('ix_ai_docs_address_id'))

    op.drop_table('ai_docs')
    # ### end Alembic commands ###
