"""add unique constraint audit_address to scope_addresses

Revision ID: a4e8a095470d
Revises: 5761c0caff77
Create Date: 2026-03-13 16:00:33.476500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4e8a095470d'
down_revision: Union[str, Sequence[str], None] = '5761c0caff77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_addresses', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_scope_address_audit_address', ['audit_id', 'address'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_scope_address_audit_address', type_='unique')

    # ### end Alembic commands ###
