"""add ai provider and api key to user

Revision ID: afb90b9643e5
Revises: 7411a65eeb96
Create Date: 2026-02-17 22:25:21.480321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afb90b9643e5'
down_revision: Union[str, Sequence[str], None] = '7411a65eeb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_provider', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True))
        batch_op.add_column(sa.Column('ai_api_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_api_key')
        batch_op.drop_column('ai_provider')

    # ### end Alembic commands ###
