"""add mythril tables

Revision ID: b8a3e5f2fd28
Revises: 3ae4048aa179
Create Date: 2026-04-15 23:59:52.758202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8a3e5f2fd28'
down_revision: Union[str, Sequence[str], None] = '3ae4048aa179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mythril_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=False),
    sa.Column('preset', sa.Enum('standard', 'deep', 'thorough', name='mythril_preset', native_enum=False), server_default=sa.text("'standard'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='mythril_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('mythril_version', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('stderr_output', sa.Text(), nullable=True),
    sa.Column('count_high', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_medium', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_low', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mythril_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mythril_runs_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mythril_runs_scope_contract_id'), ['scope_contract_id'], unique=False)

    op.create_table('mythril_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=False),
    sa.Column('swc_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('high', 'medium', 'low', name='mythril_severity', native_enum=False), nullable=False),
    sa.Column('contract', sa.Text(), nullable=True),
    sa.Column('function_name', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('lineno', sa.Integer(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('min_gas_used', sa.Integer(), nullable=True),
    sa.Column('max_gas_used', sa.Integer(), nullable=True),
    sa.Column('tx_sequence', sa.JSON(), nullable=True),
    sa.Column('source_map', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['mythril_runs.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mythril_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mythril_issues_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mythril_issues_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mythril_issues_scope_contract_id'), ['scope_contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mythril_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mythril_issues_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_mythril_issues_run_id'))
        batch_op.drop_index(batch_op.f('ix_mythril_issues_audit_id'))

    op.drop_table('mythril_issues')
    with op.batch_alter_table('mythril_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mythril_runs_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_mythril_runs_audit_id'))

    op.drop_table('mythril_runs')
    # ### end Alembic commands ###
