"""add etherscan api key to user

Revision ID: bb0ac7541add
Revises: ec59dfc0daab
Create Date: 2026-03-13 11:13:34.414125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb0ac7541add'
down_revision: Union[str, Sequence[str], None] = 'ec59dfc0daab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etherscan_api_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('etherscan_api_key')

    # ### end Alembic commands ###
