"""add slither tables

Revision ID: bda500e7d7ea
Revises: a4b2951697fc
Create Date: 2026-04-13 20:24:41.311997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bda500e7d7ea'
down_revision: Union[str, Sequence[str], None] = 'a4b2951697fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slither_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='slither_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('slither_version', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('stderr_output', sa.Text(), nullable=True),
    sa.Column('count_high', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_medium', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_low', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_informational', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('count_optimization', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slither_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slither_runs_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slither_runs_scope_contract_id'), ['scope_contract_id'], unique=False)

    op.create_table('slither_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=False),
    sa.Column('check', sa.Text(), nullable=False),
    sa.Column('impact', sa.Enum('high', 'medium', 'low', 'informational', 'optimization', name='slither_impact', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='slither_confidence', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('elements', sa.JSON(), nullable=True),
    sa.Column('slither_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['slither_runs.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slither_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slither_findings_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slither_findings_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slither_findings_scope_contract_id'), ['scope_contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slither_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slither_findings_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_slither_findings_run_id'))
        batch_op.drop_index(batch_op.f('ix_slither_findings_audit_id'))

    op.drop_table('slither_findings')
    with op.batch_alter_table('slither_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slither_runs_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_slither_runs_audit_id'))

    op.drop_table('slither_runs')
    # ### end Alembic commands ###
