"""add_scope_contract_id_to_analyzer4_runs

Revision ID: d0980cda7662
Revises: 21e5d4b37e2c
Create Date: 2026-05-12 10:26:38.964556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0980cda7662'
down_revision: Union[str, Sequence[str], None] = '21e5d4b37e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer4_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope_contract_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_analyzer4_runs_scope_contract_id'), ['scope_contract_id'], unique=False)
        batch_op.create_foreign_key('fk_analyzer4_runs_scope_contract_id', 'scope_contracts', ['scope_contract_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer4_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_analyzer4_runs_scope_contract_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_analyzer4_runs_scope_contract_id'))
        batch_op.drop_column('scope_contract_id')

    # ### end Alembic commands ###
