"""add decompiled_sol and abi_json to scope_addresses

Revision ID: db9bc4a54b8d
Revises: f1e2d3c4b5a6
Create Date: 2026-03-26 15:20:21.230515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db9bc4a54b8d'
down_revision: Union[str, Sequence[str], None] = 'f1e2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decompiled_sol', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('abi_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_addresses', schema=None) as batch_op:
        batch_op.drop_column('abi_json')
        batch_op.drop_column('decompiled_sol')

    # ### end Alembic commands ###
