"""add_solparsing_tables

Revision ID: ec1012541e69
Revises: a4e8a095470d
Create Date: 2026-03-15 13:09:47.692085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec1012541e69'
down_revision: Union[str, Sequence[str], None] = 'a4e8a095470d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('scope_contract_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('contract_kind', sa.Enum('contract', 'library', 'interface', 'abstract', name='parsed_contract_kind', native_enum=False), nullable=False),
    sa.Column('inheritance', sa.JSON(), nullable=True),
    sa.Column('source_line_start', sa.Integer(), nullable=True),
    sa.Column('source_line_end', sa.Integer(), nullable=True),
    sa.Column('slither_id', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'parsing', 'parsed', 'analyzed', 'error', name='parse_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['scope_contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_contract_id', 'name', name='uq_parsed_contracts_file_name')
    )
    with op.batch_alter_table('parsed_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_contracts_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parsed_contracts_scope_contract_id'), ['scope_contract_id'], unique=False)

    op.create_table('parsed_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('parsed_contract_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('topic0', sa.Text(), nullable=True),
    sa.Column('natspec', sa.JSON(), nullable=True),
    sa.Column('source_line_start', sa.Integer(), nullable=True),
    sa.Column('source_line_end', sa.Integer(), nullable=True),
    sa.Column('slither_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['parsed_contract_id'], ['parsed_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parsed_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_events_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parsed_events_parsed_contract_id'), ['parsed_contract_id'], unique=False)

    op.create_table('parsed_functions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('parsed_contract_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('selector', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'external', 'internal', 'private', name='fn_visibility', native_enum=False), nullable=True),
    sa.Column('mutability', sa.Enum('pure', 'view', 'payable', 'nonpayable', name='fn_mutability', native_enum=False), nullable=True),
    sa.Column('is_constructor', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_receive', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('return_params', sa.JSON(), nullable=True),
    sa.Column('modifiers_applied', sa.JSON(), nullable=True),
    sa.Column('natspec', sa.JSON(), nullable=True),
    sa.Column('source_line_start', sa.Integer(), nullable=True),
    sa.Column('source_line_end', sa.Integer(), nullable=True),
    sa.Column('reads_var_ids', sa.JSON(), nullable=True),
    sa.Column('writes_var_ids', sa.JSON(), nullable=True),
    sa.Column('has_reentrancy', sa.Boolean(), nullable=True),
    sa.Column('is_entry_point', sa.Boolean(), nullable=True),
    sa.Column('slither_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['parsed_contract_id'], ['parsed_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parsed_functions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_functions_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parsed_functions_parsed_contract_id'), ['parsed_contract_id'], unique=False)

    op.create_table('parsed_modifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('parsed_contract_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'external', 'internal', 'private', name='mod_visibility', native_enum=False), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('natspec', sa.JSON(), nullable=True),
    sa.Column('source_line_start', sa.Integer(), nullable=True),
    sa.Column('source_line_end', sa.Integer(), nullable=True),
    sa.Column('slither_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['parsed_contract_id'], ['parsed_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parsed_modifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_modifiers_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parsed_modifiers_parsed_contract_id'), ['parsed_contract_id'], unique=False)

    op.create_table('parsed_state_variables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('parsed_contract_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type_str', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'external', 'internal', 'private', name='var_visibility', native_enum=False), nullable=True),
    sa.Column('is_constant', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('storage_slot', sa.Integer(), nullable=True),
    sa.Column('initial_value', sa.Text(), nullable=True),
    sa.Column('natspec', sa.JSON(), nullable=True),
    sa.Column('source_line_start', sa.Integer(), nullable=True),
    sa.Column('source_line_end', sa.Integer(), nullable=True),
    sa.Column('slither_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['parsed_contract_id'], ['parsed_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parsed_state_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_state_variables_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parsed_state_variables_parsed_contract_id'), ['parsed_contract_id'], unique=False)

    op.create_table('call_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('caller_function_id', sa.Uuid(), nullable=False),
    sa.Column('callee_function_id', sa.Uuid(), nullable=True),
    sa.Column('call_type', sa.Enum('internal', 'external', 'delegatecall', 'staticcall', 'library_call', name='call_edge_type', native_enum=False), nullable=False),
    sa.Column('is_cross_contract', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('callee_expression', sa.Text(), nullable=True),
    sa.Column('callee_signature', sa.Text(), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['callee_function_id'], ['parsed_functions.id'], ),
    sa.ForeignKeyConstraint(['caller_function_id'], ['parsed_functions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_edges_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_edges_callee_function_id'), ['callee_function_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_edges_caller_function_id'), ['caller_function_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_edges_caller_function_id'))
        batch_op.drop_index(batch_op.f('ix_call_edges_callee_function_id'))
        batch_op.drop_index(batch_op.f('ix_call_edges_audit_id'))

    op.drop_table('call_edges')
    with op.batch_alter_table('parsed_state_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_state_variables_parsed_contract_id'))
        batch_op.drop_index(batch_op.f('ix_parsed_state_variables_audit_id'))

    op.drop_table('parsed_state_variables')
    with op.batch_alter_table('parsed_modifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_modifiers_parsed_contract_id'))
        batch_op.drop_index(batch_op.f('ix_parsed_modifiers_audit_id'))

    op.drop_table('parsed_modifiers')
    with op.batch_alter_table('parsed_functions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_functions_parsed_contract_id'))
        batch_op.drop_index(batch_op.f('ix_parsed_functions_audit_id'))

    op.drop_table('parsed_functions')
    with op.batch_alter_table('parsed_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_events_parsed_contract_id'))
        batch_op.drop_index(batch_op.f('ix_parsed_events_audit_id'))

    op.drop_table('parsed_events')
    with op.batch_alter_table('parsed_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_contracts_scope_contract_id'))
        batch_op.drop_index(batch_op.f('ix_parsed_contracts_audit_id'))

    op.drop_table('parsed_contracts')
    # ### end Alembic commands ###
