"""add scope tables

Revision ID: ec59dfc0daab
Revises: 73d964339333
Create Date: 2026-03-02 01:03:36.306179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec59dfc0daab'
down_revision: Union[str, Sequence[str], None] = '73d964339333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('github', 'etherscan', 'arbiscan', 'polygonscan', 'bscscan', 'basescan', 'optimism', 'upload', 'bug_bounty', name='scope_source_type', native_enum=False), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('commit_hash', sa.Text(), nullable=True),
    sa.Column('contract_address', sa.Text(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('platform_name', sa.Text(), nullable=True),
    sa.Column('contest_id', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_status', sa.Enum('pending', 'fetching', 'success', 'failed', name='scope_fetch_status', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_sources_audit_id'), ['audit_id'], unique=False)

    op.create_table('scope_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('sloc', sa.Integer(), nullable=False),
    sa.Column('is_in_scope', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('scope_reason', sa.Text(), nullable=True),
    sa.Column('compiler_version', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['scope_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_contracts_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scope_contracts_source_id'), ['source_id'], unique=False)

    op.create_table('scope_addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('address_type', sa.Enum('deployment', 'proxy', 'implementation', 'role', 'token', 'external', 'other', name='scope_address_type', native_enum=False), nullable=False),
    sa.Column('role_name', sa.Text(), nullable=True),
    sa.Column('proxy_type', sa.Text(), nullable=True),
    sa.Column('implementation_address', sa.Text(), nullable=True),
    sa.Column('contract_id', sa.Uuid(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['scope_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_addresses_audit_id'), ['audit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scope_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_addresses_audit_id'))

    op.drop_table('scope_addresses')
    with op.batch_alter_table('scope_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_contracts_source_id'))
        batch_op.drop_index(batch_op.f('ix_scope_contracts_audit_id'))

    op.drop_table('scope_contracts')
    with op.batch_alter_table('scope_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_sources_audit_id'))

    op.drop_table('scope_sources')
    # ### end Alembic commands ###
