"""add_audit_notes_table

Revision ID: f551a15097c3
Revises: 495e477a5a60
Create Date: 2026-05-20 01:19:21.810076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f551a15097c3'
down_revision: Union[str, Sequence[str], None] = '495e477a5a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_notes_audit_id'), ['audit_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_notes_audit_id'))

    op.drop_table('audit_notes')
    # ### end Alembic commands ###
